<?php
/**
 * Created by PhpStorm.
 * User: yunliang
 * Date: 2015/12/30
 * Time: 9:44
 */
class RsManagerAction extends AdminbaseAction
{
    protected $users;
    protected $zhuCai;
    protected $ziYuanDan;
    protected $category;
    protected $suppliers;
    protected $savepath;
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->users=M('cmf_users','ecs_');
        $this->zhuCai=M('goods_zhucai','ecs_');
        $this->ziYuanDan=M('goods_ziyuandan','ecs_');
        $this->category=M('goods_category_zhucai','ecs_');
        $this->suppliers=M('suppliers','ecs_');
        $this->savepath=APP_PATH."../attachs/ziyuandan/";
        vendor('PHPExcel.PHPExcel');
        import('ORG.Net.UploadFile');
        vendor('Flourish.api');
        api::run();
    }

    function upload()
    {
        if(!is_dir($this->savepath)){
            mkdir($this->savepath,0777,true);//todo 因为有子目录需要开启递归
        }
        $upload=new UploadFile();
        $upload->maxSize=1024*1024*5;
        $upload->allowExts=array('xls','xlsx');
        $upload->savePath=$this->savepath;
        $upload->saveRule=get_current_admin_id().'_'.time();
        if(!$upload->upload()){
            $this->error($upload->getErrorMsg());
        }else {
            return $upload->getUploadFileInfo();
        }
    }

    function index()
    {
        //获取当前的管理员
        $admin_id=get_current_admin_id();
        $name=$this->users->where("id=$admin_id")->getfield('user_nicename');
        $this->assign('name',$name);
        //todo 一级分类
        $cate=$this->category->where("grade=2")->select();
        $this->assign('cate',$cate);
        //todo 二级分类
        if(I("get.cid")){
            $cid=I("get.cid");
            $res=$this->category->where("parent_id=$cid")->select();
            $this->assign('res',$res);
            $this->assign('cateid',$cid);
        }

        //todo 供应商
        $sups=$this->suppliers->field('suppliers_id,suppliers_name')->select();
        $this->assign('sups',$sups);
        $count=$this->ziYuanDan->where("is_delete=0 and user_id=$admin_id")->count();
        $page=$this->page($count,5);
        $list=$this->ziYuanDan->order('ziyuandan_id')
            ->where("is_delete=0 and user_id=$admin_id")
            ->limit($page->firstRow.','.$page->listRows)
            ->select();
        $this->assign('page',$page->show("Admin"));
        $this->assign('list',$list);
        $this->display();
    }

    function add_post()
    {
        $info=$this->upload();
        $path=str_replace($this->savepath,'',$info[0]['savename']);
        if(IS_POST){
            if(!I("post.goods_cat2")){
                $this->error("请选择一级分类");
            }
            $first=I("post.goods_cat2");
            if(!I("post.goods_cat3")){
                $this->error("请选择二级分类");
            }
            $second=I("post.goods_cat3");
            $data['ziyuandan_cat']=json_encode(array($first=>$second));
            $data['ziyuandan_type']=2;//todo 后台管理员
            if(!I("post.suppliers_person")){
                $this->error("请填写联系人");
            }
            $data['suppliers_person']=I("post.suppliers_person");
            if(!I("post.suppliers_mobile")){
                $this->error("请填写联系方式");
            }
            $data['suppliers_mobile']=I("post.suppliers_mobile");
            $data['user_id']=get_current_admin_id();
            $data['suppliers_id']=I('post.suppliers_id');
            $data['is_delete']=0;
            if(!I("post.title")){
                $this->error("标题很重要……");
            }
            $data['title']=I("post.title");
            $data['file_url']=$path;
            $data['file_name']=$info[0]['name'];
            $data['add_time']=time();
            $data['update_time']=time();
            if(!I("post.description")){
                $this->error("描述信息很重要……");
            }
            $data['description']=I("post.description");
            $json=json_encode(array($first=>$second));
            $temp=json_decode($json,true);
            $str='';
            foreach($temp as $k=>$v){
                $str.=$k.',';
                if(is_array($v)){
                    $str.=join(',',$v);
                }else{
                    $str.=$v.',';
                }
            }
            $res=$this->category->where("goods_category_id in ($str)")->field('goods_category_name')->select();
            foreach($res as $item){
                $string.=$item['goods_category_name'].' ';
            }
            $data['keyword']=$string;
            $this->ziYuanDan->add($data);

            //todo 解析excel
            $model=D('ecs_Resource');
            $res=$model->parseEXCEL($info[0]['savename']);
            //print_r($res);
            $count=count($res);
            //todo 先把id 传过去
            $ziyuandan_id=$this->ziYuanDan->order('ziyuandan_id DESC')->limit('1')->getfield('ziyuandan_id');
            for($i=2;$i<=$count;$i++)
            {
                $data['ziyuandan_id']=$ziyuandan_id;
                $data['goods_cat']=$res[$i][0];
                $data['goods_name']=$res[$i][1];
                $data['goods_version']=$res[$i][2];
                $data['brand_name']=$res[$i][3];
                $data['goods_color']=$res[$i][4];
                $data['goods_unit']=$res[$i][5];
                $data['public_price']=$res[$i][6];
                $data['shop_price']=$res[$i][7];
                $data['stock']=$res[$i][8];
                $data['goods_desc']=$res[$i][9];
                $data['is_delete']=0;
                $data['add_time']=time();
                $this->zhuCai->add($data);
            }
            $this->success('发布成功！',U('RsManager/index'));
        }
    }


    function edit()
    {
        //todo 一级分类
        $cate=$this->category->where("grade=2")->select();
        $this->assign('cate',$cate);

        //todo 供应商
        $sups=$this->suppliers->field('suppliers_id,suppliers_name')->select();
        $this->assign('sups',$sups);

        $zid=intval(I("get.zid"));
        $data=$this->ziYuanDan->where("ziyuandan_id=$zid")->find();
        $category=json_decode($data['ziyuandan_cat'],true);
        foreach($category as $k=>$v){
            //dump($k);3
            //dump($v);array(5) { [0]=> string(1) "9" [1]=> string(2) "59" [2]=> string(2) "25" [3]=> string(2) "57" [4]=> string(2) "58" }
            $first=$k;
            $item=implode(',',$v);
            $res=$this->category->where("goods_category_id in ($item)")->select();
        }
        $this->assign('second',$item);
        if(I("get.cid")){
            $cid=I("get.cid");
            $res=$this->category->where("parent_id=$cid")->select();
            $this->assign('res',$res);
            $first=$cid;
            $this->assign('first',$first);
        }
        $this->assign('res',$res);
        $this->assign('first',$first);
        $this->assign('data',$data);
        $this->display();
    }

    function edit_post()
    {
        //todo 上传功能
        $info=$this->upload();
        $path=str_replace($this->savepath,'',$info[0]['savename']);
        $zid=I("post.zid");
        //todo 表单提交
        if(IS_POST){
            if(!I("post.goods_cat2")){
                $this->error("请选择一级分类");
            }
            $first=I("post.goods_cat2");
            if(!I("post.goods_cat3")){
                $this->error("请选择二级分类");
            }
            $second=I("post.goods_cat3");
            $data['ziyuandan_cat']=json_encode(array($first=>$second));
            $data['ziyuandan_type']=2;//todo 后台管理员
            if(!I("post.suppliers_person")){
                $this->error("请填写联系人");
            }
            $data['suppliers_person']=I("post.suppliers_person");
            if(!I("post.suppliers_mobile")){
                $this->error("请填写联系方式");
            }
            $data['suppliers_mobile']=I("post.suppliers_mobile");
            $data['user_id']=get_current_admin_id();
            $data['suppliers_id']=I('post.suppliers_id');
            $data['is_delete']=0;
            if(!I("post.title")){
                $this->error("标题很重要……");
            }
            $data['title']=I("post.title");
            $data['file_url']=$path;
            $data['file_name']=$info[0]['name'];
            $data['update_time']=time();
            if(!I("post.description")){
                $this->error("描述信息很重要……");
            }
            $data['description']=I("post.description");
            $json=json_encode(array($first=>$second));
            $temp=json_decode($json,true);
            $str='';
            foreach($temp as $k=>$v){
                $str.=$k.',';
                if(is_array($v)){
                    $str.=join(',',$v);
                }else{
                    $str.=$v.',';
                }
            }

            $res=$this->category->where("goods_category_id in ($str)")->field('goods_category_name')->select();

            foreach($res as $item){
                $string.=$item['goods_category_name'].' ';
            }
            $data['keyword']=$string;

            $model=new Model();
            $model->startTrans();
            $msg=$this->ziYuanDan->where("ziyuandan_id=$zid")->getfield("file_url");
            if(file_exists($this->savepath.$msg))
                unlink($this->savepath.$msg);
            if($this->ziYuanDan->where("ziyuandan_id= $zid")->save($data)){
                $model->commit();
            }else{
                $model->rollback();
            }



            //todo 解析excel
            $model=D('ecs_Resource');
            $res=$model->parseEXCEL($info[0]['savename']);
            $count=count($res);
            for($i=2;$i<=$count;$i++)
            {
                $data['ziyuandan_id']=$zid;
                $data['goods_cat']=$res[$i][0];
                $data['goods_name']=$res[$i][1];
                $data['goods_version']=$res[$i][2];
                $data['brand_name']=$res[$i][3];
                $data['goods_color']=$res[$i][4];
                $data['goods_unit']=$res[$i][5];
                $data['public_price']=$res[$i][6];
                $data['shop_price']=$res[$i][7];
                $data['stock']=$res[$i][8];
                $data['goods_desc']=$res[$i][9];
                $data['is_delete']=0;
                $data['add_time']=time();
                $this->zhuCai->where("ziyuandan_id=$zid")->save($data);
            }
            $this->success('修改成功！',U('RsManager/index'));
        }
    }

    //todo 下载
    function Download($file,$showname)
    {
        $zid=intval(I("zid"));
        $times=$this->ziYuanDan->where("ziyuandan_id=$zid")->getfield("download_time");
        $data['download_time']=$times+1;
        $this->ziYuanDan->where("ziyuandan_id=$zid")->save($data);

        header("Content-type:text/html;charset=utf-8");
        $filepath=iconv('UTF-8','GB2312',$this->savepath.$file);
        if(!file_exists($filepath)){
            echo "文件不存在";
            return;
        }
        $fp=fopen($this->savepath.$file,"r");
        //取得文件大小
        $file_Size=filesize($this->savepath.$file);

        header("Content-type:application/octet-stream");
        header("Accept-Ranges:bytes");
        header("Accept-Length:".$file_Size);
        $ua = $_SERVER["HTTP_USER_AGENT"];

        $encoded_filename = urlencode($showname);
        $encoded_filename = str_replace("+", "%20", $encoded_filename);

        header('Content-Type: application/octet-stream');

        if (preg_match("/MSIE/", $ua)) {
            header('Content-Disposition: attachment; filename="' . $encoded_filename . '"');
        } else if (preg_match("/Firefox/", $ua)) {
            header('Content-Disposition: attachment; filename*="utf8\'\'' . $showname . '"');
        } else {
            header('Content-Disposition: attachment; filename="' . $showname . '"');
        }
        $buffer=1024;
        $buffer_count=0;
        while(!feof($fp)&&$file_Size-$buffer_count>0){
            $data=fread($fp,$buffer);
            $buffer_count+=$buffer;
            echo $data;
        }
        fclose($fp);
    }
    
    //todo 删除
    function delete()
    {
        $zid=intval(I('get.zid'));
        $data['is_delete']=1;
        $flog=$this->ziYuanDan->where("ziyuandan_id=$zid")->save($data);
        if($flog)
            $this->success('删除成功',U('RsManager/index'));
    }

    //todo 资源单详情
    function getList()
    {
        $zid=intval(I("get.zid"));
        $bind=$this->ziYuanDan->where("ziyuandan_id=$zid")->getfield('file_name');
        $res=$this->zhuCai->where("ziyuandan_id=$zid")->select();
        $this->assign('res',$res);
        $this->assign('bind',$bind);
        $this->display('list');
    }

    /**
    //todo 导入
    function FileImport($filename,$exts)
    {
        $phpexcel=new PHPExcel();
        //todo 判断excel文档类型
        if($exts=='xls'){
            $phpread=PHPExcel_IOFactory::createReader('Excel5');
        }else if($exts=='xlsx'){
            $phpread=PHPExcel_IOFactory::createReader('Excel2007');
        }
        //todo 加载文件
        $phpxls=$phpread->load($filename,$encode='utf-8');
        $currentsheet=$phpxls->getSheet(0);//todo 暂时只获取第一个表单数据
        $rows=$currentsheet->getHighestRow();//todo 获取总行数
        $columns=$currentsheet->getHighestColumn();//todo 获取总列数
        $arrExcel=$phpxls->getSheet(0)->toArray();
        //todo 读取数据 第一行不需要
        $ziyuandan_id=$this->ziYuanDan->order('ziyuandan_id DESC')->limit('1')->getfield('ziyuandan_id');
        //file_put_contents("text.txt",$ziyuandan_id);
        for($row=2;$row<=$rows;$row++){
            $data['ziyuandan_id']=$ziyuandan_id;
            $data['goods_cat']=$phpxls->getActiveSheet()->getCell("A".$row)->getValue();
            $data['goods_name']=$phpxls->getActiveSheet()->getCell("B".$row)->getValue();
            $data['goods_version']=$phpxls->getActiveSheet()->getCell("C".$row)->getValue();
            $data['brand_name']=$phpxls->getActiveSheet()->getCell("D".$row)->getValue();
            $data['goods_color']=$phpxls->getActiveSheet()->getCell("E".$row)->getValue();
            $data['goods_unit']=$phpxls->getActiveSheet()->getCell("F".$row)->getValue();
            $data['shop_price']=$phpxls->getActiveSheet()->getCell("G".$row)->getValue();
            $data['public_price']=$phpxls->getActiveSheet()->getCell("H".$row)->getValue();
            $data['stock']=$phpxls->getActiveSheet()->getCell("I".$row)->getValue();
            $data['goods_desc']=$phpxls->getActiveSheet()->getCell("J".$row)->getValue();
            $data['add_time']=time();
            $data['is_delete']=0;
            $flog=$this->zhuCai->add($data);
            if(!$flog){
                $this->error("请确认资源单格式正确");
            }
        }
    }
    //todo 数据库导出
    function FileOutPut($data,$filename='导出资源单')
    {
        $row=2;
        $phpexcel=new PHPExcel();
        header('Content-Type:application/vnd.ms-excel');
        header('Content-Disposition:attachment;filename='.$filename.'.xls');
        foreach($data as $k=>$rows){
            $span=ord("A");//todo 返回ASCII 码值
            foreach($rows as $key=>$value){
                $column=chr($span);//todo 返回字符串
                //$phpexcel->setCellValue($column.$row,$value);
                $phpexcel->getActiveSheet(0)->setCellValue($column.$row,$value);
                $span++;
            }
            $row++;
        }
        $phpexcel->setActiveSheetIndex(0);
        $phpread=PHPExcel_IOFactory::createWriter($phpexcel,'Excel2007');
        $phpread->save('php://output');
    }



            $dh=opendir($this->savepath);
            while ($file=readdir($dh)) {
                if ($file != "." && $file != "..") {
                    $fullpath = $this->savepath . "/" . $file;
                    if (!is_dir($fullpath)) {
                        unlink($fullpath);
                    } else {
                        deldir($fullpath);
                    }
                }
            }
     */



}
