<?php
/**
 * Created by PhpStorm.
 * User: yunliang
 * Date: 2015/12/1
 * Time: 17:53
 */
class CustomerAction extends AdminbaseAction
{
    protected $buyers;
    protected $purchase;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->buyers=M('temp_buyers','ecs_');
        $this->purchase=M('temp_purchase','ecs_');
    }

    public function index(){
        $count=$this->buyers->where("invitation_person= 0")->count();
        $page=$this->page($count,20);

        $res=$this->buyers->where("invitation_person= 0")
            ->order('add_time DESC')
            ->limit($page->firstRow.','.$page->listRows)
            ->select();

        foreach($res as $key=>$val){
            $bid=$val['temp_buyers_id'];
            $orders=$this->purchase->where("buyers_id=$bid and state in (1,2,3,4)")->select();//->where("state in (1,2,3,4)")
            $res[$key]['orders']=count($orders);

            for($i=0;$i<count($orders);$i++){
                $res[$key]['moneys']+=$orders[$i]['money'];
            }
        }

        $this->assign('page',$page->show("Admin"));
        $this->assign('list',$res);
        $this->display();
    }

}