<?php
/**
 * Created by PhpStorm.
 * User: yunliang
 * Date: 2015/12/7
 * Time: 10:05
 */
class InvitationAction extends AdminbaseAction
{
    protected $buyers;
    protected $purchase;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->buyers=M('temp_buyers','ecs_');
        $this->purchase=M('temp_purchase','ecs_');
    }

    public function index()
    {
        //$id=intval(I("get.id"));
        $id=207;
        $name=$this->buyers->where("temp_buyers_id=$id")->field('nick')->find();
        $this->assign('name',$name);


        $count=$this->buyers->where("invitation_person=$id")->count();
        $page=$this->page($count,10);
        $res2=$this->buyers
            ->where("invitation_person=$id")
            ->limit($page->firstRow.','.$page->listRows)
            ->select();

        foreach($res2 as $key=>$val){
            $bid=$val['temp_buyers_id'];
            $orders=$this->purchase->where("buyers_id=$bid")->select();
            $res2[$key]['orders']=count($orders);

            for($i=0;$i<count($orders);$i++){
                $res2[$key]['moneys']+=$orders[$i]['money'];
            }
        }
        $this->assign('page',$page->show("Admin"));
        $this->assign('list',$res2);
        $this->display();
    }
}