<?php
/**
 * Created by PhpStorm.
 * User: yunliang
 * Date: 2015/12/22
 * Time: 18:18
 */

class PurchaselistAction extends AdminbaseAction
{
    protected $buyers;
    protected $purchase;
    protected $purchase_goods;
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->purchase=M('temp_purchase','ecs_');
        $this->buyers=M('temp_buyers','ecs_');
        $this->purchase_goods=M('temp_purchase_goods','ecs_');
    }

    public function index(){
        $id=intval(I("get.id"));

        $name=$this->buyers->where("temp_buyers_id=$id")->getfield('nick');
        $count=$this->purchase
            ->where("buyers_id=$id and state in(1,2,3,4)")
            ->count();

        $page=$this->page($count,5);

        $data=$this->purchase
            ->where("buyers_id=$id and state in(1,2,3,4)")
            ->field('temp_purchase_id,temp_purchase_sn,suppliers_name,money,name,mobile,address,time,finish_time,description,suppliers_remarks,state,method')
            ->order('temp_purchase_id')
            ->limit($page->firstRow.','.$page->listRows)
            ->select();
        foreach($data as $k=>$v){
            $pid=$v['temp_purchase_id'];
            $data[$k]['goods']=$this->purchase_goods->where("temp_purchase_id=$pid")
                ->field('version,unit,amount*price as xiaoji,brand_name,goods_color,goods_sn')
                ->select();
        }
        //var_dump($data);
        $this->assign('list',$data);
        $this->assign('page',$page->show("Admin"));
        $this->assign('name',$name);
        $this->display();
    }
}