<?php
/**
 * Created by PhpStorm.
 * User: yunliang
 * Date: 2015/12/30
 * Time: 9:44
 */
class RsManagerAction extends AdminbaseAction
{
    protected $users;
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->users=M('cmf_users','ecs_');
    }

    function index()
    {
        //获取当前的管理员
        $admin_id=get_current_admin_id();
        $name=$this->users->where("id=$admin_id")->getfield('user_nicename');
        $this->assign('name',$name);
        $this->display();
    }
}
